/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.JadwalDokterController;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class DokterView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardDokterView
     */
    private JadwalDokterController jdc;
    private int idJadwal = 0;
    private String idPendaftaran = null;

//    private javax.swing.event.ChangeListener jamMulaiListener;
//    private javax.swing.event.ChangeListener jamSelesaiListener;
//    private boolean programmaticUpdate = false;
    public DokterView() {
        initComponents();
        tampilkanDaftarPasien();

    }

    public DokterView(String idDokter, String nama_dokter) {
        initComponents();
        
        this.jLabel1.setText("Selamat Datang " + nama_dokter);
        this.jLabel3.setText(nama_dokter);
        this.jLabel10.setText(nama_dokter);

        this.jdc = new JadwalDokterController(idDokter);
        
        // Setup Tabel Jadwal (Tab 1, 2, 3)
        DefaultTableModel dtm = this.jdc.createTable();
        this.TabelTambah.setModel(dtm);
        this.TabelUpdate.setModel(dtm);
        this.TabelHapus.setModel(dtm);
        this.jdc.tampilkanJadwalDokter();
        
        tampilkanDaftarPasien(); // <-- Tambahkan baris ini
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelTambah = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spKuota = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spJamSelesai = new javax.swing.JSpinner();
        btnTambah = new javax.swing.JButton();
        spJamMulai = new javax.swing.JSpinner();
        spTanggal = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spUJamMulai = new javax.swing.JSpinner();
        spUJamSelesai = new javax.swing.JSpinner();
        btnUpdate = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabelUpdate = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        spUTanggal = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spUKuota = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        lblUIdJadwal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelHapus = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        lblDIdJadwal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnTidak = new javax.swing.JButton();
        btnYa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        btnUpdateStatus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelStatus = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 202, 228));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JADWAL DOKTER");

        jTabbedPane4.setBackground(new java.awt.Color(255, 255, 153));

        jPanel2.setBackground(new java.awt.Color(144, 224, 239));

        TabelTambah.setBackground(new java.awt.Color(204, 255, 255));
        TabelTambah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelTambah);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama            : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Kuota           ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jam Mulai            : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Jam Selesai          : ");

        spJamSelesai.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        spJamSelesai.setEditor(new javax.swing.JSpinner.DateEditor(spJamSelesai, "HH:mm"));

        btnTambah.setBackground(new java.awt.Color(102, 255, 204));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        spJamMulai.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        spJamMulai.setEditor(new javax.swing.JSpinner.DateEditor(spJamMulai, "HH:mm"));

        spTanggal.setModel(new javax.swing.SpinnerDateModel());
        spTanggal.setEditor(new javax.swing.JSpinner.DateEditor(spTanggal, "dd/MM/yyyy"));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tanggal          : ");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spKuota, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(spJamSelesai))
                                .addGap(33, 33, 33)
                                .addComponent(btnTambah))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(spJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spKuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Tambah", jPanel2);

        jPanel3.setBackground(new java.awt.Color(144, 224, 239));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nama            : ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Kuota           ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Jam Mulai            : ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Jam Selesai          : ");

        spUJamMulai.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        spUJamMulai.setEditor(new javax.swing.JSpinner.DateEditor(spUJamMulai, "HH:mm"));

        spUJamSelesai.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        spUJamSelesai.setEditor(new javax.swing.JSpinner.DateEditor(spUJamSelesai, "HH:mm"));

        btnUpdate.setBackground(new java.awt.Color(102, 255, 204));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        TabelUpdate.setBackground(new java.awt.Color(204, 255, 255));
        TabelUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TabelUpdate);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tanggal               : ");

        spUTanggal.setModel(new javax.swing.SpinnerDateModel());
        spUTanggal.setEditor(new javax.swing.JSpinner.DateEditor(spUTanggal, "dd/MM/yyyy"));

        jLabel10.setText("jLabel10");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("ID Jadwal");

        lblUIdJadwal.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUIdJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spUKuota, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spUJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spUJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spUTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(spUJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(spUJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUIdJadwal)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(spUTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spUKuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addGap(26, 26, 26))
        );

        jTabbedPane4.addTab("Update", jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        TabelHapus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDeleteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelHapus);

        jLabel16.setText("ID Jadwal");

        lblDIdJadwal.setText("-");

        jLabel17.setText("Apakah anda yakin ingin menghapus jadwal tersebut?");

        btnTidak.setText("Clear");
        btnTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTidakActionPerformed(evt);
            }
        });

        btnYa.setText("Hapus");
        btnYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnYa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTidak))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(45, 45, 45)
                            .addComponent(lblDIdJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblDIdJadwal))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTidak)
                    .addComponent(btnYa))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Hapus", jPanel5);

        jPanel4.setBackground(new java.awt.Color(144, 224, 239));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Status");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diterima", "Ditolak", "Menunggu", " " }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(102, 255, 204));
        btnUpdateStatus.setText("Update");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        tabelStatus.setBackground(new java.awt.Color(204, 255, 255));
        tabelStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelStatusMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelStatus);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                .addComponent(btnUpdateStatus)
                .addGap(16, 16, 16))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateStatus))
                .addGap(13, 13, 13))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        jTabbedPane4.addTab("Verifikasi", jPanel4);

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        // 1. Menghubungkan dengan Controller

        // (controller sudah dibuat di constructor DokterView)
        if (this.jdc == null) {
            JOptionPane.showMessageDialog(this, "Controller belum diinisialisasi. Silakan login ulang.");
            return;
        }

        // 2. Persiapan nilai input
        try {
            int kuota = (int) spKuota.getValue();

            // ambil tanggal dari spinnerTanggal
            // (Date) mengubah value dari objek menjadi Date
            java.sql.Date sqlTanggal = java.sql.Date.valueOf(((Date) spTanggal.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate());

            // ambil jam mulai
            java.sql.Time sqlJamMulai = java.sql.Time.valueOf(((Date) spJamMulai.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalTime().withSecond(0).withNano(0));

            // ambil jam selesai
            java.sql.Time sqlJamSelesai = java.sql.Time.valueOf(((Date) spJamSelesai.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalTime().withSecond(0).withNano(0));

            // 3. Memanggil method tambahJadwalDokter
            boolean status = jdc.tambahJadwalDokter(kuota, sqlJamMulai, sqlJamSelesai, sqlTanggal);

            // 4. Jika berhasil
            if (status == true) {

                // Autorefresh tabel
                DefaultTableModel dtm = jdc.createTable();
                this.TabelTambah.setModel(dtm);
                this.TabelUpdate.setModel(dtm);
                this.TabelHapus.setModel(dtm);
                jdc.tampilkanJadwalDokter();

                JOptionPane.showMessageDialog(this, "Berhasil menambah jadwal");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambah jadwal");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Input tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // 1. Menghubungkan dengan Controller

        // (controller sudah dibuat di constructor DokterView)
        System.out.println("DEBUG IDs: idJadwal=" + idJadwal + ", idDokter=" + this.jdc.getIdDokter());
        System.out.println("DEBUG spinner raw: spJamMulai.class=" + spJamMulai.getValue().getClass().getName() + ", value=" + spJamMulai.getValue());
        if (this.jdc == null) {
            JOptionPane.showMessageDialog(this, "Controller belum diinisialisasi. Silakan login ulang.");
            return;
        }

        // 2. Persiapan nilai input
        try {
            int kuota = (int) spUKuota.getValue();

            // Ambil nilai dari spinner sebagai java.util.Date (jelas)
            java.util.Date utilTanggal = (java.util.Date) spUTanggal.getValue();
            java.util.Date utilJamMulai = (java.util.Date) spUJamMulai.getValue();
            java.util.Date utilJamSelesai = (java.util.Date) spUJamSelesai.getValue();

            // Pastikan idJadwal sudah ada (tidak 0)
            if (idJadwal <= 0) {
                JOptionPane.showMessageDialog(this, "Pilih jadwal yang akan diubah terlebih dahulu.");
                return;
            }

            // Konversi ke java.sql.* dengan cara paling sederhana
            java.sql.Date sqlTanggal = new java.sql.Date(utilTanggal.getTime());
            // Untuk jam, kita ingin hanya waktu (hh:mm:ss) — java.sql.Time cukup dari getTime()
            java.sql.Time sqlJamMulai = new java.sql.Time(utilJamMulai.getTime());
            java.sql.Time sqlJamSelesai = new java.sql.Time(utilJamSelesai.getTime());

            // Panggil controller update
            boolean status = jdc.ubahJadwalDokter(kuota, sqlJamMulai, sqlJamSelesai, sqlTanggal, idJadwal);

            if (status) {
                DefaultTableModel dtm = jdc.createTable();
                this.TabelTambah.setModel(dtm);
                this.TabelUpdate.setModel(dtm);
                this.TabelHapus.setModel(dtm);
                jdc.tampilkanJadwalDokter();
                JOptionPane.showMessageDialog(this, "Berhasil mengubah jadwal");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah jadwal");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Input tidak valid: " + e.getMessage());
            e.printStackTrace();
        }
        System.out.println("DEBUG IDs: idJadwal=" + idJadwal + ", idDokter=" + this.jdc.getIdDokter());

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        // Coding untuk meng-get data dari tabel bagian yang di klik
        // 1. Siapkan data DTM baru
        DefaultTableModel dtm2 = (DefaultTableModel) this.TabelUpdate.getModel();
        int pilih = this.TabelUpdate.getSelectedRow();

        // Ambil ID jadwal
        this.idJadwal = Integer.parseInt(dtm2.getValueAt(pilih, 0).toString());
        this.lblUIdJadwal.setText(String.valueOf(idJadwal));

        // Ambil tanggal (sql.Date → util.Date)
        java.sql.Date sqlTanggal = (java.sql.Date) dtm2.getValueAt(pilih, 2);
        this.spUTanggal.setValue(new java.util.Date(sqlTanggal.getTime()));

        // Ambil jam mulai
        java.sql.Time sqlJamMulai = (java.sql.Time) dtm2.getValueAt(pilih, 3);
        this.spUJamMulai.setValue(new java.util.Date(sqlJamMulai.getTime()));

        // Ambil jam selesai
        java.sql.Time sqlJamSelesai = (java.sql.Time) dtm2.getValueAt(pilih, 4);
        this.spUJamSelesai.setValue(new java.util.Date(sqlJamSelesai.getTime()));

        // Ambil kuota → ke spinner
        int kuota = Integer.parseInt(dtm2.getValueAt(pilih, 5).toString());
        this.spUKuota.setValue(kuota);

//        programmaticUpdate = true;
//        try {
//            spTanggal.setValue(new java.util.Date(sqlTanggal.getTime()));
//            spJamMulai.setValue(new java.util.Date(sqlJamMulai.getTime()));
//            spJamSelesai.setValue(new java.util.Date(sqlJamSelesai.getTime()));
//            spUKuota.setValue(kuota);
//        } finally {
//            programmaticUpdate = false;
//        }
    }//GEN-LAST:event_TableMouseClicked

    private void btnYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYaActionPerformed
        // TODO add your handling code here:
        // Persiapan nilai
        int id = Integer.parseInt(this.lblDIdJadwal.getText());

// 🔹 Tampilkan konfirmasi hapus
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Anda yakin ingin menghapus jadwal dokter ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

// Jika user pilih "Tidak", hentikan proses hapus
        if (konfirmasi != JOptionPane.YES_OPTION) {
            return;
        }

// Panggil method hapus
        boolean status = jdc.hapusJadwalDokter(id);

        if (status == true) {
            // Auto refresh
            DefaultTableModel dtm = jdc.createTable();
            this.TabelTambah.setModel(dtm);
            this.TabelUpdate.setModel(dtm);
            this.TabelHapus.setModel(dtm);
            jdc.tampilkanJadwalDokter();

            JOptionPane.showMessageDialog(this, "Berhasil hapus data");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal hapus data");
        }

    }//GEN-LAST:event_btnYaActionPerformed

    private void TableDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDeleteMouseClicked
        // TODO add your handling code here:// 1. Siapkan data DTM baru
        DefaultTableModel dtm2 = (DefaultTableModel) this.TabelHapus.getModel();
        int pilih = this.TabelHapus.getSelectedRow();

        // Ambil ID jadwal
        this.idJadwal = Integer.parseInt(dtm2.getValueAt(pilih, 0).toString());
        this.lblDIdJadwal.setText(String.valueOf(idJadwal));
    }//GEN-LAST:event_TableDeleteMouseClicked

    private void btnTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTidakActionPerformed
        // TODO add your handling code here:
        this.lblDIdJadwal.setText("-");
    }//GEN-LAST:event_btnTidakActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        if (idPendaftaran == null || idPendaftaran.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih pasien terlebih dahulu!");
            return;
        }

        String statusBaru = cbStatus.getSelectedItem().toString();
        boolean berhasil = jdc.updateStatusPasien(idPendaftaran, statusBaru);

        if (berhasil) {
            JOptionPane.showMessageDialog(this, "Status berhasil diupdate!");
            tampilkanDaftarPasien();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengupdate status.");
        }

    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void tabelStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelStatusMouseClicked
        int row = tabelStatus.getSelectedRow();

    if (row > -1) {
        idPendaftaran = tabelStatus.getValueAt(row, 0).toString();

        String status = tabelStatus.getValueAt(row, 4).toString();
        cbStatus.setSelectedItem(status);
    }
    }//GEN-LAST:event_tabelStatusMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         // 1. Tampilkan Popup Konfirmasi (Yes/No)
        int jawaban = JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda yakin ingin Logout?", 
            "Konfirmasi Logout", 
            JOptionPane.YES_NO_OPTION
        );
        
        // 2. Cek Jawaban User
        if (jawaban == JOptionPane.YES_OPTION) {
            // Jika pilih YES:
            
            // Bersihkan data session (Logout)
            Utility.UserSession.clear();
            
            // Buka kembali halaman Login
            new LoginView().setVisible(true);
            
            // Tutup halaman Dashboard saat ini
            this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed
    }
    // ==========================================
    // LOGIKA TAB VERIFIKASI (Perbaikan)
    // ==========================================

    // 1. Method untuk menampilkan data ke jTable3
    private void tampilkanDaftarPasien() {
        // Asumsi: Controller kamu punya method 'getDaftarPasien()'
        // Jika belum ada, kamu harus membuatnya di JadwalDokterController
        if (this.jdc != null) {
            DefaultTableModel dtmPasien = this.jdc.getDaftarPasien(); 
            this.tabelStatus.setModel(dtmPasien);
        }
    }

    // 2. Event saat Baris Tabel Verifikasi (jTable3) diklik
    private void TableVerifikasiMouseClicked(java.awt.event.MouseEvent evt) {
        int baris = tabelStatus.getSelectedRow();

    if (baris > -1) {

        // Ambil ID janji (STRING)
        this.idPendaftaran = tabelStatus.getValueAt(baris, 0).toString();

        // Ambil status dari kolom 4
        Object statusObj = tabelStatus.getValueAt(baris, 4);
        if (statusObj != null) {
            cbStatus.setSelectedItem(statusObj.toString());
        }
    }
        
        
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DokterView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelHapus;
    private javax.swing.JTable TabelTambah;
    private javax.swing.JTable TabelUpdate;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTidak;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JButton btnYa;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel lblDIdJadwal;
    private javax.swing.JLabel lblUIdJadwal;
    private javax.swing.JSpinner spJamMulai;
    private javax.swing.JSpinner spJamSelesai;
    private javax.swing.JSpinner spKuota;
    private javax.swing.JSpinner spTanggal;
    private javax.swing.JSpinner spUJamMulai;
    private javax.swing.JSpinner spUJamSelesai;
    private javax.swing.JSpinner spUKuota;
    private javax.swing.JSpinner spUTanggal;
    private javax.swing.JTable tabelStatus;
    // End of variables declaration//GEN-END:variables
}
