/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.JanjiController;
import Controller.PasienController;
import Utility.ComboItem;
import Utility.UserSession;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */


public class PasienView extends javax.swing.JFrame {
    PasienController pasienController;
    JanjiController janjiController;
    // untuk menyimpan hasil pilihan dialog
    private int pickedIdJadwal = -1;
    private String pickedJadwalText = null;

   
    /**
     * Creates new form DashboardUserView
     */
    /**
     * Creates new form DashboardUserView
     */
    public PasienView() {
    initComponents();

    if (UserSession.getNama() == null) {
        JOptionPane.showMessageDialog(this, "Session tidak ditemukan! Silakan login ulang.");
        dispose();
        new LoginView().setVisible(true);
        return;
    }

    pasienController = new PasienController();
    janjiController = new JanjiController();

    myCustomInit();
}

      
    private void myCustomInit() {

    // Nama dari session
    lblTampilNama.setText("Halo, " + UserSession.getNama());

    // 🔹 Ambil umur dari database
    String idPasien = UserSession.getIdPasien();
    int umur = pasienController.getUmurPasien(idPasien);

    if (umur > 0) {
        lblUmur.setText("Umur : " + umur + " tahun");
    } else {
        lblUmur.setText("Umur : -");
    }

    refreshTabelStatus();
    setLocationRelativeTo(null);
}

    
    // ===============================
// POPUP PILIH JADWAL
// ===============================
private void openPilihJadwalPopup() {

    PilihJadwal dialog = new PilihJadwal(
            this,
            (idJadwal, summary) -> {
                pickedIdJadwal = idJadwal;
                pickedJadwalText = summary;
                lblJadwalTerpilih.setText("Dipilih: " + summary);
            }
    );

    dialog.setVisible(true);
}


    
    // ================= KIRIM JANJI TEMU =================
    public void aksiSimpanJanji() {

    String idPasien = UserSession.getIdPasien(); 
    String keluhan = txtKeluhan.getText().trim();

    if (keluhan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Mohon isi keluhan Anda!");
        return;
    }

    if (pickedIdJadwal == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih jadwal terlebih dahulu!");
        return;
    }

    boolean berhasil = janjiController.tambahJanjiTemu(pickedIdJadwal, idPasien, keluhan);

    if (berhasil) {
        JOptionPane.showMessageDialog(this, "Berhasil! Janji Temu telah dibuat.");
        bersihkanForm();
        refreshTabelStatus();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan. Silakan coba lagi.");
    }
}


    // Method untuk membersihkan form input
    private void bersihkanForm() {
    txtKeluhan.setText("");
    pickedIdJadwal = -1;
    pickedJadwalText = null;
    lblJadwalTerpilih.setText("Belum memilih jadwal");
    }

    
    
    // Method untuk me-refresh tabel status (Tab 2)
    private void refreshTabelStatus() {
    try {
        DefaultTableModel model = janjiController.createTable();
        tabelStatus.setModel(model);
        janjiController.tampilkanRiwayat();
    } catch (Exception ex) {
        System.out.println("Gagal refresh tabel: " + ex.getMessage());
    }
}

    
    private void clearStatusTable() {
    DefaultTableModel model = (DefaultTableModel) tabelStatus.getModel();
    model.setRowCount(0); // hapus semua baris
}
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeluhan = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        btnKirimPermintaan = new javax.swing.JButton();
        lblJadwal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTampilNama = new javax.swing.JLabel();
        btnCariJadwal = new javax.swing.JButton();
        lblJadwalTerpilih = new javax.swing.JLabel();
        lblUmur = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelStatus = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnClearTbl = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 202, 228));

        jLabel1.setBackground(new java.awt.Color(0, 119, 182));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD PASIEN");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 153));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(144, 224, 239));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FORMULIR KELUHAN & PILIH DOKTER");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tuliskan Keluhan Anda :");

        txtKeluhan.setBackground(new java.awt.Color(204, 255, 255));
        txtKeluhan.setColumns(20);
        txtKeluhan.setRows(5);
        jScrollPane1.setViewportView(txtKeluhan);

        btnClear.setBackground(new java.awt.Color(255, 255, 153));
        btnClear.setForeground(new java.awt.Color(51, 51, 51));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnKirimPermintaan.setBackground(new java.awt.Color(255, 255, 153));
        btnKirimPermintaan.setForeground(new java.awt.Color(51, 51, 51));
        btnKirimPermintaan.setText("Kirim Permintaan");
        btnKirimPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimPermintaanActionPerformed(evt);
            }
        });

        lblJadwal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJadwal.setForeground(new java.awt.Color(51, 51, 51));
        lblJadwal.setText("Pilih Jadwal :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Selamat Datang,");

        lblTampilNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTampilNama.setForeground(new java.awt.Color(51, 51, 51));
        lblTampilNama.setText("-");

        btnCariJadwal.setBackground(new java.awt.Color(255, 255, 153));
        btnCariJadwal.setForeground(new java.awt.Color(0, 0, 0));
        btnCariJadwal.setText("Cari Jadwal");
        btnCariJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariJadwalActionPerformed(evt);
            }
        });

        lblJadwalTerpilih.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJadwalTerpilih.setForeground(new java.awt.Color(51, 51, 51));
        lblJadwalTerpilih.setText("Belum Memilih Jadwal.");

        lblUmur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUmur.setForeground(new java.awt.Color(0, 0, 0));
        lblUmur.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCariJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblJadwalTerpilih)
                                            .addComponent(lblJadwal)))
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTampilNama))
                                    .addComponent(lblUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKirimPermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTampilNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUmur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJadwalTerpilih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCariJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKirimPermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Buat Janji Temu", jPanel2);

        jPanel3.setBackground(new java.awt.Color(144, 224, 239));

        tabelStatus.setBackground(new java.awt.Color(204, 255, 255));
        tabelStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelStatusMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelStatus);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Riwayat Pengajuan Janji Temu");

        btnClearTbl.setBackground(new java.awt.Color(255, 255, 153));
        btnClearTbl.setForeground(new java.awt.Color(0, 0, 0));
        btnClearTbl.setText("Clear");
        btnClearTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClearTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnClearTbl)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status Janji Temu", jPanel3);

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKirimPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimPermintaanActionPerformed
        aksiSimpanJanji();
    }//GEN-LAST:event_btnKirimPermintaanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        bersihkanForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnClearTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTblActionPerformed
        clearStatusTable();
    }//GEN-LAST:event_btnClearTblActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // 1. Tampilkan Popup Konfirmasi (Yes/No)
        int jawaban = JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda yakin ingin Logout?", 
            "Konfirmasi Logout", 
            JOptionPane.YES_NO_OPTION
        );
        
        // 2. Cek Jawaban User
        if (jawaban == JOptionPane.YES_OPTION) {
            // Jika pilih YES:
            
            // Bersihkan data session (Logout)
            Utility.UserSession.clear();
            
            // Buka kembali halaman Login
            new LoginView().setVisible(true);
            
            // Tutup halaman Dashboard saat ini
            this.dispose();
        } 
        // Jika pilih NO, tidak terjadi apa-apa (tetap di dashboard)
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCariJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariJadwalActionPerformed
       openPilihJadwalPopup();
    }//GEN-LAST:event_btnCariJadwalActionPerformed

    private void tabelStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelStatusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelStatusMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariJadwal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearTbl;
    private javax.swing.JButton btnKirimPermintaan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblJadwal;
    private javax.swing.JLabel lblJadwalTerpilih;
    private javax.swing.JLabel lblTampilNama;
    private javax.swing.JLabel lblUmur;
    private javax.swing.JTable tabelStatus;
    private javax.swing.JTextArea txtKeluhan;
    // End of variables declaration//GEN-END:variables
}
